#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 14 08:30:14 2017

@author: Marcus Naslund 
"""

import schprog as SP

""" initialize designer """
mDes = SP.Designer()
""" initialize ISO """
# (designCateory)
mISO = SP.ISO12215('A')
""" initialize vessel """
# (LWL, bC, mLDC, beta04, hT, tC, V)
mVess = SP.Vessel(2.6, 1.3, 600, 10.0, 3.0, 0.875, 6.0)
""" initialize structure """
mStruct = SP.Structure()

""" create materials """
# (matLabel, yieldStrength, tensileStrength, elasticModulus, shearModulus, density)
mAL_5083_O = SP.MaterialsLibrary('AL_5083_O', 125, 270, 7000, 2692, 2720)
#AL_6082_T6 = SP.MaterialsLibrary('AL_6082_T6', 115, 170, 7000, 2692, 2830)

""" create plates """
mPlaLib = SP.PlatingLibrary()
# (label, tp)
mAL3 = SP.Plates('AL3', 3)
mAL4 = SP.Plates('AL4', 4)
mAL5 = SP.Plates('AL5', 5)
mAL6 = SP.Plates('AL6', 6)
mAL8 = SP.Plates('AL8', 8)
mPlaLib.assign_plate(mAL3)
mPlaLib.assign_plate(mAL4)
mPlaLib.assign_plate(mAL5)
mPlaLib.assign_plate(mAL6)
mPlaLib.assign_plate(mAL8)

""" create panels """
# (b, lPan, xPos, yPos, location)
mPan1 = SP.Panel(366, 2400, 1.2, 0.366/2, 'side')
mPan2 = SP.Panel(280, 2500, 1.2, 0.280/2, 'bottom')

""" assign panels to mStructure """
mStruct.assign_panel(mPan1)
mStruct.assign_panel(mPan2)

""" assign mStructure to mVessel """
mVess.assign_structure(mStruct)

""" calculate pressure using mISO rules """
mDes.calc_pressure_factors(mISO, mStruct, mVess) # objStruct.Panel[i].'pressure factors'
                                                 # [ruleType, kDC, kL, kAR_d, kAR_p, kZ]
mDes.calc_design_pressures(mISO, mStruct, mVess) # objStruct.Panel[i].'scantling requirements'
                                                 # [ruleType, pMax]

""" if you wanna assign material to a specific panel """
#mStruct.Panel[i].assign_material(mAL_5083_O) # mStruct.Panel[i].Material
""" if you wanna assign the same material to all panels """
mDes.assign_material_to_all_panels(mStruct, mAL_5083_O) # mStruct.Panel[i].Material

""" calculate scnatling requirement """
mDes.calc_scantling_req(mISO, mStruct, mVess) # objStruct.Panel[i].'scantling requirements'
                                              # [ruleType, k2, k3, FShear, MBend, tReq, tMin]

""" assign recommended plate to all panels """
mDes.assign_recommended_plates(mStruct, mPlaLib) # objStruct.Panel[i].Plate

print('Done')


